/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AnunciarImovelRouteImport } from './routes/anunciar-imovel'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'

const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarImovelRoute = AnunciarImovelRouteImport.update({
  id: '/anunciar-imovel',
  path: '/anunciar-imovel',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ImoveisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/anunciar-imovel': typeof AnunciarImovelRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/imoveis/$id': typeof ImoveisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/anunciar-imovel': typeof AnunciarImovelRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/imoveis/$id': typeof ImoveisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/anunciar-imovel': typeof AnunciarImovelRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/imoveis/$id': typeof ImoveisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anunciar'
    | '/anunciar-imovel'
    | '/contato'
    | '/imoveis'
    | '/imoveis/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anunciar'
    | '/anunciar-imovel'
    | '/contato'
    | '/imoveis'
    | '/imoveis/$id'
  id:
    | '__root__'
    | '/'
    | '/anunciar'
    | '/anunciar-imovel'
    | '/contato'
    | '/imoveis'
    | '/imoveis/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciarRoute: typeof AnunciarRoute
  AnunciarImovelRoute: typeof AnunciarImovelRoute
  ContatoRoute: typeof ContatoRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar-imovel': {
      id: '/anunciar-imovel'
      path: '/anunciar-imovel'
      fullPath: '/anunciar-imovel'
      preLoaderRoute: typeof AnunciarImovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof ImoveisRoute
    }
  }
}

interface ImoveisRouteChildren {
  ImoveisIdRoute: typeof ImoveisIdRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisIdRoute: ImoveisIdRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciarRoute: AnunciarRoute,
  AnunciarImovelRoute: AnunciarImovelRoute,
  ContatoRoute: ContatoRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
